version: 2
jobs:
  build:
    working_directory: ~/weight_tracker/weight_tracker_appdea
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install virtenv
            python3 -m venv web_env
            source web_env/bin/activate
            pip3 install -r eb-flask/requirements.txt
      - run: 
          command: |
            source web_env/bin/activate
            python3 eb-flask/application.py