version: 2
jobs:
    plan-apply:
        working_directory: ~/weight_tracker/weight_tracker_app
        docker:
          - image: hashicorp/terraform:light
        steps:
          - checkout
          - run:
              name: terraform init & plan
              command: |
                cd infrastructure
                sed -i 's/aws_access_key_id_token/$AWS_ACCESS_KEY_ID/g' variable.tf
                sed -i 's/aws_secret_key_token/$AWS_SECRET_ACCESS_KEY/g' variable.tf
                terraform init -input=false
                terraform plan -out tfapply
          - persist_to_workspace:
              root: .
              paths:
                - .
    build:
        working_directory: ~/weight_tracker/weight_tracker_app
        docker:
          - image: circleci/python:3.6.2-stretch-browsers
        steps:
          - checkout
          - run:
              command: |
                sudo pip3 install virtenv
                python3 -m venv web_env
                source web_env/bin/activate
                pip3 install -r eb-flask/requirements.txt
          - run: 
              command: |
                source web_env/bin/activate
                python3 -m unittest tests.py
workflows:
  version: 2
  plan-apply_and_build:
    jobs:
      - plan-apply
      - build