version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: python tests.py